spring:
  datasource:
#    url: jdbc:postgresql://rain.db.elephantsql.com:5432/chghxyzz
#    username: chghxyzz
#    password: 4U24j4wIDU0KI2WLIps7SiIUC-jDBSCl
    url: jdbc:postgresql://localhost:5432/DataSA
    username: postgres
    password: root

#spring:
#  jpa:
#    show-sql: true

# online postgres
#spring:
#  datasource:
#    url: jdbc:postgresql://john.db.elephantsql.com:5432/bcslnnov
#    username: bcslnnov
#    password: ZSYlCcUbdDwLwNa3E-j_nUBhUc9bkWTf

# local Postgres
  main:
    allow-bean-definition-overriding: true

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create


  #allow table's name like tblProduct

#spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  properties:
    hibernate:
      format_sql: true

  servlet:
    multipart:
      enabled: true
logging:
  level:
    org:
      springframework:
        security: trace
